image:
  file: Dockerfile
tasks:
  - command: |
      # set java version to the latest installed
      latest_java=$(sdk list java | awk '/installed/ {print $NF}'|sort -V|tail -n 1) && sdk default java $latest_java
      # set language of Filius
      sudo sed -i 's/# locale=en_GB/locale=en_GB/' /etc/filius/filius.ini
      # link 'filius bestanden'
      ln -s '/workspace/filius/filius bestanden' '/home/gitpod/filius bestanden'
      sleep 2
      ln -s '/workspace/filius/filius bestanden' '/home/gitpod/Desktop/filius bestanden'
      # create filius start icon on desktop
      cp /usr/share/applications/filius.desktop /home/gitpod/Desktop/
      chmod +x /home/gitpod/Desktop/filius.desktop
      # start filius
      filius &
      # wait for FILIUS window
      while ! wmctrl -l| grep -q FILIUS ; do sleep 1; echo "wait for FILIUS window"; done
      # maximize filius window
      wmctrl -r 'FILIUS' -b add,maximized_horz,maximized_vert
      # wmctrl -r ':ACTIVE:' -b add,full_screen // alternative
      
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
